module.exports = {
  MAP_WIDTH: 2000,
  MAP_HEIGHT: 2000,
  PLAYER_RADIUS: 20,
  PROJECTILE_RADIUS: 4,
  PROJECTILE_SPEED: 400,
  PROJECTILE_LIFETIME: 1500,
  ZOMBIE_SPEED: 80,
  ZOMBIE_SPAWN_INTERVAL: 10, // seconds
  ZOMBIE_RADIUS: 18,
};